# Generated by Django 4.2.6 on 2023-10-17 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_destination_desc'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductsOffered',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('label', models.CharField(max_length=10)),
                ('category', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('img', models.ImageField(upload_to='media/')),
            ],
        ),
    ]
