# Generated by Django 4.2.6 on 2023-10-17 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_productsoffered'),
    ]

    operations = [
        migrations.AddField(
            model_name='productsoffered',
            name='st',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
